# Generated by Django 4.2.3 on 2023-10-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityEvents', '0002_event_registration_email_event_registration_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_registration',
            name='event',
            field=models.IntegerField(null=True),
        ),
    ]
