# Generated by Django 4.2.4 on 2023-10-03 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityEvents', '0004_alter_event_registration_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_registration',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ActivityEvents.events'),
        ),
    ]
