# Generated by Django 4.2.6 on 2023-10-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityEvents', '0009_alter_customuser_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoplereviews',
            name='image',
            field=models.ImageField(null=True, upload_to='media/images/'),
        ),
    ]
