# Generated by Django 4.2.6 on 2023-10-15 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityEvents', '0009_alter_customuser_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AskaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(default=datetime.date(2023, 10, 15), null=True),
        ),
    ]
