# Generated by Django 4.2.6 on 2023-10-26 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityEvents', '0010_alter_peoplereviews_image'),
        ('ActivityEvents', '0010_askaquestion_alter_events_event_date'),
    ]

    operations = [
    ]
